// ./crates/pyenv-core/src/meta/public_docs/core.rs
//! Core selection and installation command docs for built-in help and completions.

use super::super::docs::CommandDoc;

pub(super) const CORE_COMMAND_DOCS: &[CommandDoc] = &[
    CommandDoc {
        name: "help",
        summary: "Display help for a command",
        usage: "Usage: pyenv help [--usage] [COMMAND]",
        help: &[
            "Shows a short summary for all primary commands, or detailed help for one command.",
            "Use `pyenv help --usage <command>` to print only the usage line.",
            "",
            "Examples:",
            "  pyenv help            Show all commands with summaries",
            "  pyenv help install    Show detailed help for the install command",
            "  pyenv help --usage global   Show only the usage line for global",
        ],
        completions: &["--usage"],
    },
    CommandDoc {
        name: "commands",
        summary: "List all available pyenv commands",
        usage: "Usage: pyenv commands [--sh|--no-sh]",
        help: &[
            "Lists the commands available from the native core and discovered plugins.",
            "Use `--sh` to show shell-helper commands, or `--no-sh` to suppress them.",
        ],
        completions: &["--sh", "--no-sh"],
    },
    CommandDoc {
        name: "local",
        summary: "Set or show the local application-specific Python version",
        usage: "Usage: pyenv local [-f|--force] [--unset] [version ...]",
        help: &[
            "Sets or displays the Python version for the current directory by writing",
            "a `.python-version` file. When no version argument is given, prints the",
            "currently configured local version.",
            "",
            "The `-f|--force` flag allows writing a version even if it is not installed.",
            "`--unset` removes the `.python-version` file from the current directory.",
            "",
            "Version prefixes like `3.12` are resolved to the latest matching installed version.",
            "",
            "Examples:",
            "  pyenv local 3.13.12     Set the local version to 3.13.12",
            "  pyenv local 3.12        Set local to the latest installed 3.12.x",
            "  pyenv local 3.13.12/envs/app   Bind the directory to a managed venv",
            "  pyenv local --unset     Remove local version setting",
            "  pyenv local             Show the currently configured local version",
            "",
            "See also: pyenv global, pyenv shell, pyenv versions, pyenv venv",
        ],
        completions: &["-f", "--force", "--unset"],
    },
    CommandDoc {
        name: "global",
        summary: "Set or show the global Python version",
        usage: "Usage: pyenv global [--unset] [version ...]",
        help: &[
            "Sets or displays the default Python version used system-wide by writing",
            "the global version file under PYENV_ROOT. When no version argument is",
            "given, prints the currently configured global version.",
            "",
            "`--unset` removes the global version file entirely, reverting to `system`.",
            "",
            "Version prefixes like `3.12` are resolved to the latest matching installed version.",
            "Multiple versions can be specified to set a priority list.",
            "",
            "Examples:",
            "  pyenv global 3.13.12       Set the global version to 3.13.12",
            "  pyenv global 3.12          Set global to the latest installed 3.12.x",
            "  pyenv global 3.13.12/envs/tooling  Make a managed venv the global default",
            "  pyenv global 3.12 3.11     Set a fallback chain: prefer 3.12, then 3.11",
            "  pyenv global --unset       Remove global version setting",
            "  pyenv global               Show the currently configured global version",
            "",
            "See also: pyenv local, pyenv shell, pyenv install, pyenv venv",
        ],
        completions: &["--unset"],
    },
    CommandDoc {
        name: "shell",
        summary: "Set or show the shell-specific Python version",
        usage: "Usage: pyenv shell [--unset|-] [version ...]",
        help: &[
            "Sets the PYENV_VERSION environment variable for the current shell session.",
            "This takes the highest priority and overrides both local and global settings.",
            "",
            "Requires shell integration from `pyenv init`. Run `pyenv init` for setup instructions.",
            "",
            "Use `--unset` to clear the shell-specific selection.",
            "Use `-` to revert to the previously selected shell version.",
            "",
            "Examples:",
            "  pyenv shell 3.13.12       Use 3.13.12 in this shell session only",
            "  pyenv shell --unset       Clear the shell-specific version",
            "  pyenv shell -             Revert to the previous shell version",
            "",
            "See also: pyenv init, pyenv global, pyenv local",
        ],
        completions: &["--unset", "-"],
    },
    CommandDoc {
        name: "install",
        summary: "Install a Python version",
        usage: "Usage: pyenv install [-l|--list] [--known] [--family <family>] [--dry-run] [--json] [-f|--force] <version> ...",
        help: &[
            "Downloads and installs Python runtimes into the managed versions directory.",
            "Uses native provider backends (NuGet on Windows, source builds on Linux/macOS/Android)",
            "for maximum reliability and speed.",
            "",
            "Version prefixes like `3.12` resolve to the latest available provider-backed version.",
            "",
            "Flags:",
            "  -l, --list         List all installable versions from native providers",
            "  --known            List from the embedded known-versions catalog instead",
            "  --family <name>    Filter --list by runtime family (cpython, pypy)",
            "  --dry-run          Show what would be installed without downloading anything",
            "  --json             Output results as JSON",
            "  -f, --force        Reinstall even if the version already exists",
            "",
            "Examples:",
            "  pyenv install --list              Show all installable versions",
            "  pyenv install --list --family pypy Show only PyPy versions",
            "  pyenv install 3.13.12             Install CPython 3.13.12",
            "  pyenv install 3.12                Install the latest available 3.12.x",
            "  pyenv install pypy3.11            Install the latest PyPy 3.11",
            "  pyenv install --dry-run 3.12      Preview what would be installed",
            "  pyenv install -f 3.13.12          Force reinstall 3.13.12",
            "",
            "See also: pyenv uninstall, pyenv versions, pyenv global",
        ],
        completions: &[
            "-l",
            "--list",
            "--known",
            "--family",
            "--dry-run",
            "--json",
            "-f",
            "--force",
        ],
    },
    CommandDoc {
        name: "available",
        summary: "List installable Python versions from native providers",
        usage: "Usage: pyenv available [--known] [--family <family>] [--json] [pattern]",
        help: &[
            "Convenience alias for provider-backed runtime discovery without needing `install --list`.",
            "This command always queries installable versions; it does not inspect already-installed runtimes.",
            "",
            "Examples:",
            "  pyenv available            Show all installable versions",
            "  pyenv available 3          Show all installable 3.x versions",
            "  pyenv available 3.12       Show all installable 3.12.x versions",
            "  pyenv available --family pypy pypy3.11",
            "",
            "See also: pyenv install --list, pyenv versions",
        ],
        completions: &["--known", "--family", "--json"],
    },
];
