// ./crates/pyenv-core/src/meta/public_docs/environment.rs
//! Runtime inspection, executable lookup, and virtual-environment command docs.

use super::super::docs::CommandDoc;

pub(super) const ENVIRONMENT_COMMAND_DOCS: &[CommandDoc] = &[
    CommandDoc {
        name: "venv",
        summary: "Manage named virtual environments under installed runtimes",
        usage: "Usage: pyenv venv <list|info|create|delete|rename|use> [options]",
        help: &[
            "Creates and manages named virtual environments under `PYENV_ROOT/venvs/<runtime>/<name>`.",
            "These env specs can be written into `.python-version` files so projects resolve",
            "to the right managed venv without requiring manual activation every time.",
            "",
            "Examples:",
            "  pyenv venv list                         Show all managed env specs",
            "  pyenv venv create 3.13 api             Create 3.13.12/envs/api",
            "  pyenv venv create 3.12 tooling --set-local",
            "  pyenv venv info api                    Show env details when the name is unique",
            "  pyenv venv use api                     Write the env spec into the current directory",
            "  pyenv venv use api --global            Make the env the global default",
            "  pyenv venv rename api api-old          Rename a managed env",
            "  pyenv venv delete api                  Remove a managed env",
            "",
            "See also: pyenv local, pyenv global, pyenv versions",
        ],
        completions: &["list", "info", "create", "delete", "rename", "use"],
    },
    CommandDoc {
        name: "uninstall",
        summary: "Uninstall Python versions",
        usage: "Usage: pyenv uninstall [-f|--force] <version> ...",
        help: &[
            "Removes managed runtimes from the versions directory and refreshes shims.",
            "Use `-f|--force` to suppress the confirmation prompt.",
            "",
            "Examples:",
            "  pyenv uninstall 3.12.10      Remove CPython 3.12.10",
            "  pyenv uninstall -f 3.11.9    Remove without confirmation",
            "",
            "See also: pyenv install, pyenv versions",
        ],
        completions: &["-f", "--force"],
    },
    CommandDoc {
        name: "rehash",
        summary: "Rebuild pyenv shims",
        usage: "Usage: pyenv rehash",
        help: &[
            "Scans all managed runtimes and regenerates shim launchers for discovered",
            "executables (python, pip, etc.). Run this after installing packages that",
            "provide new command-line tools.",
            "",
            "This is run automatically after `pyenv install` and during `pyenv init`.",
        ],
        completions: &[],
    },
    CommandDoc {
        name: "version",
        summary: "Show the current Python version and how it was selected",
        usage: "Usage: pyenv version [--bare]",
        help: &[
            "Displays the currently selected Python version(s) and how they were chosen",
            "(environment variable, .python-version file, or global version file).",
            "",
            "`--bare` prints just the version names without the origin information.",
            "",
            "Examples:",
            "  pyenv version         3.13.12 (set by C:\\Users\\Roy\\.pyenv\\version)",
            "  pyenv version --bare  3.13.12",
            "",
            "See also: pyenv versions, pyenv version-name, pyenv version-origin",
        ],
        completions: &["--bare"],
    },
    CommandDoc {
        name: "versions",
        summary: "List all installed Python versions",
        usage: "Usage: pyenv versions [--bare] [--skip-aliases] [--skip-envs] [--executables]",
        help: &[
            "Lists all Python versions installed under the managed versions directory,",
            "marking the currently selected version with an asterisk (*).",
            "",
            "Flags:",
            "  --bare           Print version names only, without the selection marker",
            "  --skip-aliases   Exclude symlink/alias entries",
            "  --skip-envs      Exclude virtualenvs",
            "  --executables    Show the executable names found in each version",
            "",
            "Examples:",
            "  pyenv versions         Show all installed versions with the active one marked",
            "  pyenv versions --bare  Print just the version names, one per line",
            "",
            "See also: pyenv version, pyenv install --list",
        ],
        completions: &["--bare", "--skip-aliases", "--skip-envs", "--executables"],
    },
    CommandDoc {
        name: "which",
        summary: "Display the full path to an executable",
        usage: "Usage: pyenv which [--nosystem] [--skip-advice] <command>",
        help: &[
            "Searches the currently selected pyenv runtimes first, then the system PATH,",
            "and prints the full path to the matching executable.",
            "",
            "`--nosystem` restricts the search to managed runtimes only.",
            "`--skip-advice` suppresses the helpful hint when the command is not found.",
            "",
            "Examples:",
            "  pyenv which python    /home/user/.pyenv/versions/3.13.12/bin/python",
            "  pyenv which pip       Show where pip resolves to",
            "",
            "See also: pyenv whence, pyenv prefix",
        ],
        completions: &["--nosystem", "--skip-advice"],
    },
    CommandDoc {
        name: "whence",
        summary: "List Python versions that contain the given executable",
        usage: "Usage: pyenv whence [--path] <command>",
        help: &[
            "Prints all managed versions that contain a matching executable.",
            "Use `--path` to show the full executable paths instead of version names.",
            "",
            "Examples:",
            "  pyenv whence python        List versions containing `python`",
            "  pyenv whence --path pip    Show full paths to `pip` in each version",
        ],
        completions: &["--path"],
    },
    CommandDoc {
        name: "exec",
        summary: "Run a command with the selected Python version",
        usage: "Usage: pyenv exec <command> [arg1 arg2...]",
        help: &[
            "Prepares PATH for the active runtime selection and then executes the",
            "requested program. Useful for running commands through a specific Python",
            "version without changing the global or local setting.",
            "",
            "Examples:",
            "  pyenv exec python -c \"import sys; print(sys.version)\"",
            "  pyenv exec pip install requests",
        ],
        completions: &[],
    },
];
