// ./crates/pyenv-core/src/meta/public_docs/system.rs
//! Root/config/help-system command docs for built-in help and completions.

use super::super::docs::CommandDoc;

pub(super) const SYSTEM_COMMAND_DOCS: &[CommandDoc] = &[
    CommandDoc {
        name: "root",
        summary: "Display the current pyenv root directory",
        usage: "Usage: pyenv root",
        help: &[
            "Prints the root directory where managed runtimes, shims, cache, and config",
            "are stored. Defaults to `~/.pyenv` unless PYENV_ROOT is set or the binary",
            "is launched from a portable layout.",
        ],
        completions: &[],
    },
    CommandDoc {
        name: "prefix",
        summary: "Display the installation prefix for one or more versions",
        usage: "Usage: pyenv prefix [version ...]",
        help: &[
            "Prints the directory path for the specified version(s). When no version",
            "is specified, prints the prefix for the currently selected version.",
            "",
            "Examples:",
            "  pyenv prefix                Show prefix for the active version",
            "  pyenv prefix 3.13.12        Show prefix for a specific version",
        ],
        completions: &[],
    },
    CommandDoc {
        name: "latest",
        summary: "Resolve the latest installed or known matching version",
        usage: "Usage: pyenv latest [-k|--known] [-b|--bypass] [-f|--force] <prefix>",
        help: &[
            "Resolves version prefixes such as `3.12` or `pypy3.11` to the latest",
            "matching version. By default, searches installed versions; use `--known`",
            "to search the full catalog instead.",
            "",
            "Examples:",
            "  pyenv latest 3.12             Latest installed 3.12.x",
            "  pyenv latest --known 3.14     Latest known 3.14.x (may not be installed)",
        ],
        completions: &["-k", "--known", "-b", "--bypass", "-f", "--force"],
    },
    CommandDoc {
        name: "hooks",
        summary: "List installed hook scripts for a given command",
        usage: "Usage: pyenv hooks <command>",
        help: &["Prints the resolved hook scripts for the requested hook name in execution order."],
        completions: &[],
    },
    CommandDoc {
        name: "shims",
        summary: "List existing pyenv shims",
        usage: "Usage: pyenv shims [--short]",
        help: &[
            "Lists the generated shim launchers under `PYENV_ROOT/shims`.",
            "Use `--short` to print command names only instead of full paths.",
            "",
            "Examples:",
            "  pyenv shims            Show full paths to all shim files",
            "  pyenv shims --short    Show just the command names (python, pip, etc.)",
        ],
        completions: &["--short"],
    },
    CommandDoc {
        name: "init",
        summary: "Configure the shell environment for pyenv",
        usage: "Usage: pyenv init [-|--path] [--detect-shell] [--no-push-path] [--no-rehash] [<shell>]",
        help: &[
            "Prints shell initialization code that adds shims to PATH, sets the PYENV_SHELL",
            "variable, and installs the `pyenv` shell function for shell-level features like",
            "`pyenv shell`.",
            "",
            "Supported shells: pwsh (PowerShell), cmd, bash, zsh, fish, sh",
            "",
            "Setup (add to your shell profile):",
            "  PowerShell:   iex ((pyenv init - pwsh) -join \"`n\")",
            "  Bash:         eval \"$(pyenv init - bash)\"",
            "  Zsh:          eval \"$(pyenv init - zsh)\"",
            "  Fish:         pyenv init - fish | source",
            "",
            "Flags:",
            "  -               Print full init code (PATH + shell function)",
            "  --path          Print only the PATH setup code",
            "  --no-push-path  Guard against duplicate shims entries in PATH",
            "  --no-rehash     Skip automatic rehash during init",
        ],
        completions: &[
            "-",
            "--path",
            "--detect-shell",
            "--no-push-path",
            "--no-rehash",
            "pwsh",
            "cmd",
            "bash",
            "zsh",
            "fish",
            "sh",
        ],
    },
    CommandDoc {
        name: "completions",
        summary: "List completions for a pyenv command",
        usage: "Usage: pyenv completions <command> [arg1 arg2...]",
        help: &[
            "Prints candidate completions for built-in commands and plugin commands that support `--complete`.",
        ],
        completions: &[],
    },
    CommandDoc {
        name: "doctor",
        summary: "Run diagnostics against the current pyenv environment",
        usage: "Usage: pyenv doctor [--json] [--fix] [-f|--force]",
        help: &[
            "Performs a series of health checks and reports potential problems:",
            "  - Verifies PYENV_ROOT exists and is accessible",
            "  - Checks that pyenv bin and shims directories are on PATH",
            "  - Detects pyenv-win conflicts (stale PYENV_ROOT, PATH shadowing)",
            "  - Warns about Windows Store Python aliases",
            "  - On Linux/macOS/Android, verifies source-build prerequisites (make, gcc/clang, etc.)",
            "",
            "Use `--json` for structured output suitable for scripts and automation.",
            "Use `--fix` to apply safe automated repairs like refreshing shims and creating",
            "the managed directory layout. Use `-f|--force` with `--fix` to skip confirmation.",
            "",
            "Examples:",
            "  pyenv doctor          Human-readable diagnostic output",
            "  pyenv doctor --json   JSON-formatted diagnostic output",
            "  pyenv doctor --fix    Prompt before applying automated fixes",
        ],
        completions: &["--json", "--fix", "-f", "--force"],
    },
    CommandDoc {
        name: "self-update",
        summary: "Check for or install the latest published pyenv-native release",
        usage: "Usage: pyenv self-update [--check] [--yes] [--force] [--github-repo <owner/repo>] [--tag <vX.Y.Z>]",
        help: &[
            "Checks GitHub releases for pyenv-native and upgrades the current portable install",
            "in place. By default it targets the latest published release for the canonical repo.",
            "",
            "Use `--check` to see whether an update is available without installing anything.",
            "Use `--tag` to reinstall or roll to a specific published release tag.",
            "Use `--yes` for unattended automation.",
            "Compatibility alias: `pyenv update` routes to the same native updater.",
            "",
            "Examples:",
            "  pyenv self-update              Update to the latest published release",
            "  pyenv self-update --check      Check whether a newer release exists",
            "  pyenv self-update --tag v0.1.8 Reinstall or pin to a specific release",
            "",
            "This command is intended for portable installs launched from PYENV_ROOT/bin.",
        ],
        completions: &["--check", "--yes", "--force", "--github-repo", "--tag"],
    },
    CommandDoc {
        name: "config",
        summary: "Inspect or change pyenv configuration",
        usage: "Usage: pyenv config path|show|get|set ...",
        help: &[
            "Reads or updates the persisted `config.toml` under the active pyenv root.",
            "",
            "Subcommands:",
            "  path              Show the path to the config file",
            "  show              Print all current configuration",
            "  get <key>         Print the value of a specific config key",
            "  set <key> <value> Update a config key",
            "",
            "Examples:",
            "  pyenv config show              Show all settings",
            "  pyenv config get install.arch   Show the configured architecture",
            "  pyenv config set install.bootstrap_pip true",
        ],
        completions: &["path", "show", "get", "set"],
    },
];
