// ./crates/pyenv-core/src/shell/emit/functions.rs
//! Shell-function wrapper emitters and command-line rendering helpers.

use std::path::Path;

use crate::shell::types::ShellKind;

use super::quotes::{cmd_quote, fish_single_quote, ps_single_quote, sh_single_quote};

pub(crate) fn render_shell_function(shell: ShellKind, exe_path: &str) -> Vec<String> {
    match shell {
        ShellKind::Pwsh => render_pwsh_shell_function(exe_path),
        ShellKind::Cmd => vec![format!(
            "doskey pyenv=for /f \"delims=\" %i in ('\"{}\" sh-cmd $*') do %i",
            exe_path
        )],
        ShellKind::Fish => render_fish_shell_function(exe_path),
        _ => render_posix_shell_function(exe_path),
    }
}

pub(crate) fn render_cmd_exec_line(exe_path: &Path, args: &[String]) -> String {
    let mut parts = vec![format!("\"{}\"", exe_path.display())];
    parts.extend(args.iter().map(|arg| cmd_quote(arg)));
    parts.join(" ")
}

fn render_pwsh_shell_function(exe_path: &str) -> Vec<String> {
    vec![
        "function Join-PyenvWindowsArguments {".to_string(),
        "  param([string[]]$PyenvArgs)".to_string(),
        "  $parts = foreach ($arg in $PyenvArgs) {".to_string(),
        "    if ($null -eq $arg) { '\"\"'; continue }".to_string(),
        "    if ($arg.Length -eq 0) { '\"\"'; continue }".to_string(),
        "    if ($arg -notmatch '[\\s\"]') { $arg; continue }".to_string(),
        "    $escaped = $arg -replace '(\\\\*)\"', '$1$1\\\"'".to_string(),
        "    $escaped = $escaped -replace '(\\\\+)$', '$1$1'".to_string(),
        "    '\"' + $escaped + '\"'".to_string(),
        "  }".to_string(),
        "  return ($parts -join ' ')".to_string(),
        "}".to_string(),
        "function Invoke-PyenvCaptured {".to_string(),
        "  param([string]$PyenvExe, [string[]]$PyenvArgs)".to_string(),
        "  $psi = [System.Diagnostics.ProcessStartInfo]::new()".to_string(),
        "  $psi.FileName = $PyenvExe".to_string(),
        "  $psi.UseShellExecute = $false".to_string(),
        "  $psi.RedirectStandardOutput = $true".to_string(),
        "  $psi.RedirectStandardError = $true".to_string(),
        "  $psi.WorkingDirectory = (Get-Location).Path".to_string(),
        "  if ($psi.PSObject.Properties.Name -contains 'ArgumentList' -and $null -ne $psi.ArgumentList) {".to_string(),
        "    foreach ($arg in $PyenvArgs) { [void]$psi.ArgumentList.Add([string]$arg) }".to_string(),
        "  } else {".to_string(),
        "    $psi.Arguments = Join-PyenvWindowsArguments $PyenvArgs".to_string(),
        "  }".to_string(),
        "  $process = [System.Diagnostics.Process]::Start($psi)".to_string(),
        "  $stdout = $process.StandardOutput.ReadToEnd()".to_string(),
        "  $stderr = $process.StandardError.ReadToEnd()".to_string(),
        "  $process.WaitForExit()".to_string(),
        "  $global:LASTEXITCODE = $process.ExitCode".to_string(),
        "  if ($stderr.Length -gt 0) { [Console]::Error.Write($stderr) }".to_string(),
        "  if ($stdout.Length -eq 0) { return @() }".to_string(),
        "  return ($stdout.TrimEnd() -split \"`r?`n\")".to_string(),
        "}".to_string(),
        "function Invoke-PyenvPassthrough {".to_string(),
        "  param([string]$PyenvExe, [string[]]$PyenvArgs)".to_string(),
        "  $psi = [System.Diagnostics.ProcessStartInfo]::new()".to_string(),
        "  $psi.FileName = $PyenvExe".to_string(),
        "  $psi.UseShellExecute = $false".to_string(),
        "  $psi.WorkingDirectory = (Get-Location).Path".to_string(),
        "  if ($psi.PSObject.Properties.Name -contains 'ArgumentList' -and $null -ne $psi.ArgumentList) {".to_string(),
        "    foreach ($arg in $PyenvArgs) { [void]$psi.ArgumentList.Add([string]$arg) }".to_string(),
        "  } else {".to_string(),
        "    $psi.Arguments = Join-PyenvWindowsArguments $PyenvArgs".to_string(),
        "  }".to_string(),
        "  $psi.RedirectStandardOutput = $false".to_string(),
        "  $psi.RedirectStandardError = $false".to_string(),
        "  $process = [System.Diagnostics.Process]::Start($psi)".to_string(),
        "  $process.WaitForExit()".to_string(),
        "  $global:LASTEXITCODE = $process.ExitCode".to_string(),
        "  return $process.ExitCode".to_string(),
        "}".to_string(),
        "function pyenv {".to_string(),
        format!("  $pyenvExe = '{}'", ps_single_quote(exe_path)),
        "  if ($args.Count -eq 0) {".to_string(),
        "    Invoke-PyenvPassthrough $pyenvExe @() | Out-Null".to_string(),
        "    return".to_string(),
        "  }".to_string(),
        "  $command = $args[0]".to_string(),
        "  $arguments = if ($args.Count -gt 1) { @($args[1..($args.Count - 1)]) } else { @() }".to_string(),
        "  switch ($command) {".to_string(),
        "    'shell' {".to_string(),
        "      $shellCmds = Invoke-PyenvCaptured $pyenvExe (@('sh-shell', '--') + @($arguments))".to_string(),
        "      if ($LASTEXITCODE -eq 0 -and $shellCmds.Count -gt 0) { Invoke-Expression ($shellCmds -join \"`n\") }".to_string(),
        "    }".to_string(),
        "    'activate' {".to_string(),
        "      $shellCmds = Invoke-PyenvCaptured $pyenvExe (@('sh-activate', '--') + @($arguments))".to_string(),
        "      if ($LASTEXITCODE -eq 0 -and $shellCmds.Count -gt 0) { Invoke-Expression ($shellCmds -join \"`n\") }".to_string(),
        "    }".to_string(),
        "    'deactivate' {".to_string(),
        "      $shellCmds = Invoke-PyenvCaptured $pyenvExe (@('sh-deactivate', '--') + @($arguments))".to_string(),
        "      if ($LASTEXITCODE -eq 0 -and $shellCmds.Count -gt 0) { Invoke-Expression ($shellCmds -join \"`n\") }".to_string(),
        "    }".to_string(),
        "    'rehash' {".to_string(),
        "      $shellCmds = Invoke-PyenvCaptured $pyenvExe (@('sh-rehash') + @($arguments))".to_string(),
        "      if ($LASTEXITCODE -eq 0 -and $shellCmds.Count -gt 0) { Invoke-Expression ($shellCmds -join \"`n\") }".to_string(),
        "    }".to_string(),
        "    default {".to_string(),
        "      Invoke-PyenvPassthrough $pyenvExe (@([string]$command) + @($arguments)) | Out-Null".to_string(),
        "    }".to_string(),
        "  }".to_string(),
        "}".to_string(),
    ]
}

fn render_fish_shell_function(exe_path: &str) -> Vec<String> {
    vec![
        "function pyenv".to_string(),
        format!("  set pyenv_exe '{}'", fish_single_quote(exe_path)),
        "  if test (count $argv) -eq 0".to_string(),
        "    $pyenv_exe".to_string(),
        "    return $status".to_string(),
        "  end".to_string(),
        "  set command $argv[1]".to_string(),
        "  set -e argv[1]".to_string(),
        "  switch \"$command\"".to_string(),
        "  case shell".to_string(),
        "    set shell_cmds ($pyenv_exe sh-shell -- $argv)".to_string(),
        "    set shell_status $status".to_string(),
        "    if test $shell_status -ne 0".to_string(),
        "      return $shell_status".to_string(),
        "    end".to_string(),
        "    if test (count $shell_cmds) -gt 0".to_string(),
        "      string join \\n -- $shell_cmds | source".to_string(),
        "    end".to_string(),
        "  case activate".to_string(),
        "    set shell_cmds ($pyenv_exe sh-activate -- $argv)".to_string(),
        "    set shell_status $status".to_string(),
        "    if test $shell_status -ne 0".to_string(),
        "      return $shell_status".to_string(),
        "    end".to_string(),
        "    if test (count $shell_cmds) -gt 0".to_string(),
        "      string join \\n -- $shell_cmds | source".to_string(),
        "    end".to_string(),
        "  case deactivate".to_string(),
        "    set shell_cmds ($pyenv_exe sh-deactivate -- $argv)".to_string(),
        "    set shell_status $status".to_string(),
        "    if test $shell_status -ne 0".to_string(),
        "      return $shell_status".to_string(),
        "    end".to_string(),
        "    if test (count $shell_cmds) -gt 0".to_string(),
        "      string join \\n -- $shell_cmds | source".to_string(),
        "    end".to_string(),
        "  case rehash".to_string(),
        "    set shell_cmds ($pyenv_exe sh-rehash $argv)".to_string(),
        "    set shell_status $status".to_string(),
        "    if test $shell_status -ne 0".to_string(),
        "      return $shell_status".to_string(),
        "    end".to_string(),
        "    if test (count $shell_cmds) -gt 0".to_string(),
        "      string join \\n -- $shell_cmds | source".to_string(),
        "    end".to_string(),
        "  case '*'".to_string(),
        "    $pyenv_exe $command $argv".to_string(),
        "  end".to_string(),
        "end".to_string(),
    ]
}

fn render_posix_shell_function(exe_path: &str) -> Vec<String> {
    vec![
        "pyenv() {".to_string(),
        format!("  pyenv_exe='{}'", sh_single_quote(exe_path)),
        "  if [ \"$#\" -eq 0 ]; then".to_string(),
        "    \"$pyenv_exe\"".to_string(),
        "    return $?".to_string(),
        "  fi".to_string(),
        "  command_name=${1:-}".to_string(),
        "  shift".to_string(),
        "  case \"$command_name\" in".to_string(),
        "    shell)".to_string(),
        "      pyenv_output=\"$(\"$pyenv_exe\" sh-shell -- \"$@\")\" || return $?".to_string(),
        "      [ -z \"$pyenv_output\" ] || eval \"$pyenv_output\"".to_string(),
        "      ;;".to_string(),
        "    activate)".to_string(),
        "      pyenv_output=\"$(\"$pyenv_exe\" sh-activate -- \"$@\")\" || return $?".to_string(),
        "      [ -z \"$pyenv_output\" ] || eval \"$pyenv_output\"".to_string(),
        "      ;;".to_string(),
        "    deactivate)".to_string(),
        "      pyenv_output=\"$(\"$pyenv_exe\" sh-deactivate -- \"$@\")\" || return $?".to_string(),
        "      [ -z \"$pyenv_output\" ] || eval \"$pyenv_output\"".to_string(),
        "      ;;".to_string(),
        "    rehash)".to_string(),
        "      pyenv_output=\"$(\"$pyenv_exe\" sh-rehash \"$@\")\" || return $?".to_string(),
        "      [ -z \"$pyenv_output\" ] || eval \"$pyenv_output\"".to_string(),
        "      ;;".to_string(),
        "    *)".to_string(),
        "      \"$pyenv_exe\" \"$command_name\" \"$@\"".to_string(),
        "      ;;".to_string(),
        "  esac".to_string(),
        "}".to_string(),
    ]
}
