[package]
name = "pyenv-gui"
version.workspace = true
edition.workspace = true
publish = false

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
tauri = { workspace = true, features = [] }
pyenv-core = { path = "../pyenv-core" }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
rfd.workspace = true
opener.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
