// ./crates/pyenv-core/src/meta/compat_docs.rs
//! Compatibility-facing command documentation for upstream-flavored aliases that are still
//! supported by the native managed-venv workflow.

use super::docs::CommandDoc;

pub(super) const COMPATIBILITY_COMMAND_DOCS: &[CommandDoc] = &[
    CommandDoc {
        name: "update",
        summary: "Compatibility alias for `pyenv self-update`",
        usage: "Usage: pyenv update [--check] [--yes] [--force] [--github-repo <owner/repo>] [--tag <vX.Y.Z>]",
        help: &[
            "Routes to the native `pyenv self-update` implementation.",
            "",
            "Use it when migrating from upstream pyenv habits, but prefer `pyenv self-update`",
            "in new documentation and automation.",
            "",
            "Examples:",
            "  pyenv update",
            "  pyenv update --check",
            "  pyenv update --tag v0.1.8",
        ],
        completions: &["--check", "--yes", "--force", "--github-repo", "--tag"],
    },
    CommandDoc {
        name: "activate",
        summary: "Compatibility alias for activating a managed virtual environment",
        usage: "Usage: pyenv activate [env-name|env-spec]",
        help: &[
            "Activates a managed virtual environment in the current shell when shell integration",
            "from `pyenv init` or `pyenv virtualenv-init -` is loaded.",
            "",
            "This compatibility command sets `PYENV_VERSION` and `VIRTUAL_ENV`, and temporarily",
            "prepends the managed env's executable directory to PATH.",
            "",
            "Examples:",
            "  pyenv activate api                  Activate a uniquely named managed env",
            "  pyenv activate 3.13.12/envs/api    Activate a fully qualified env spec",
            "  pyenv activate                     Activate the currently selected managed env",
            "",
            "Preferred long-term workflow: bind the env with `pyenv venv use <name>` so",
            "projects resolve automatically through `.python-version`.",
        ],
        completions: &[],
    },
    CommandDoc {
        name: "deactivate",
        summary: "Compatibility alias for leaving the current managed virtual environment",
        usage: "Usage: pyenv deactivate",
        help: &[
            "Restores `PYENV_VERSION`, `VIRTUAL_ENV`, and PATH after `pyenv activate`.",
            "",
            "Examples:",
            "  pyenv deactivate",
        ],
        completions: &[],
    },
    CommandDoc {
        name: "virtualenv",
        summary: "Compatibility alias for `pyenv venv create`",
        usage: "Usage: pyenv virtualenv [-f|--force] [--set-local] [runtime] <name>",
        help: &[
            "Creates a managed virtual environment using the native `pyenv venv` backend.",
            "",
            "Pass `<runtime> <name>` explicitly, or pass only `<name>` to reuse the current",
            "selected runtime. The new env is stored under `PYENV_ROOT/venvs/<runtime>/<name>`",
            "and is still referenced by the logical spec `<runtime>/envs/<name>`.",
            "",
            "Examples:",
            "  pyenv virtualenv 3.13 api",
            "  pyenv virtualenv --set-local 3.12 tooling",
            "  pyenv virtualenv api          Reuse the current selected runtime",
            "",
            "Preferred native command: `pyenv venv create <runtime> <name>`.",
        ],
        completions: &["-f", "--force", "--set-local"],
    },
    CommandDoc {
        name: "virtualenvs",
        summary: "Compatibility alias for `pyenv venv list`",
        usage: "Usage: pyenv virtualenvs [--bare] [--json]",
        help: &[
            "Lists managed virtual environments known to pyenv-native.",
            "",
            "Examples:",
            "  pyenv virtualenvs",
            "  pyenv virtualenvs --bare",
            "  pyenv virtualenvs --json",
        ],
        completions: &["--bare", "--json"],
    },
    CommandDoc {
        name: "virtualenv-delete",
        summary: "Compatibility alias for `pyenv venv delete`",
        usage: "Usage: pyenv virtualenv-delete [-f|--force] <env-name|env-spec>",
        help: &[
            "Deletes a managed virtual environment by short name or full spec.",
            "",
            "Examples:",
            "  pyenv virtualenv-delete api",
            "  pyenv virtualenv-delete -f 3.13.12/envs/api",
        ],
        completions: &["-f", "--force"],
    },
    CommandDoc {
        name: "virtualenv-prefix",
        summary: "Print the full path to a managed virtual environment",
        usage: "Usage: pyenv virtualenv-prefix [env-name|env-spec]",
        help: &[
            "Prints the managed virtual environment directory path.",
            "When no argument is provided, it uses the currently selected managed env.",
            "",
            "Examples:",
            "  pyenv virtualenv-prefix api",
            "  pyenv virtualenv-prefix",
        ],
        completions: &[],
    },
    CommandDoc {
        name: "virtualenv-init",
        summary: "Compatibility alias for shell init output that supports activate/deactivate",
        usage: "Usage: pyenv virtualenv-init [-|--path|--detect-shell] [shell]",
        help: &[
            "Prints the same shell init output as `pyenv init`, including support for",
            "compatibility commands like `pyenv activate` and `pyenv deactivate`.",
            "",
            "Examples:",
            "  eval \"$(pyenv virtualenv-init - bash)\"",
            "  iex ((pyenv virtualenv-init - pwsh) -join \"`n\")",
            "",
            "Preferred native command: `pyenv init - <shell>`.",
        ],
        completions: &["-", "--path", "--detect-shell"],
    },
];
